### ISSUE TITLE
error occurs when run with intel mpi

### ISSUE THREAD

**Issue by tzyii** [QEF/SternheimerGW#1]
I try to run the example01_Si. When i just execute the command "gw.x < pw.in > pw.out", It exits normally. But when i excute "mpirun -np 4 gw.x < pw.in > pw.out", ...
     Program SternheimerGW v.0.14 starts on 19Dec2017 at 19:25:15 

     This program is part of the open-source Quantum ESPRESSO suite
     for quantum simulation of materials; please cite
         "P. Giannozzi et al., J. Phys.:Condens. Matter 21 395502 (2009);
         "P. Giannozzi et al., J. Phys.:Condens. Matter 29 465901 (2017);
          URL http://www.quantum-espresso.org", 
     in publications or presentations arising from this work. More details at
     http://www.quantum-espresso.org/quote

     Parallel version (MPI), running on     4 processors

     MPI processes distributed on     1 nodes
     R & G space division:  proc/nbgrp/npool/nimage =       4

     Please cite SternheimerGW as:
         M. Schlipf, H. Lambert, N. Zibouche, and F. Giustino, SternheimerGW,
         paper in preparation, URL http://www.sternheimergw.org

     To increase the reproducibility of your results you can mention the
     git description of this version: unknown

     other relevant papers:
         H. Lambert and F. Giustino, Phys. Rev. B 88, 075117 (2013)
         F. Giustino, M. L. Cohen, and S. G. Louie, Phys. Rev. B 81, 115105 (2010)

     Reading data from directory:
     ./tmp/si.save/

     IMPORTANT: XC functional enforced from input :
     Exchange-correlation      = PZ ( 1  1  0  0 0 0)
     Any further DFT definition will be discarded
     Please, verify this is what you really want

 
     Parallelization info
     --------------------
     sticks:   dense  smooth     PW     G-vecs:    dense   smooth      PW
     Min          58      58     21                  569      569     132
     Max          59      59     22                  570      570     135
     Sum         235     235     85                 2277     2277     531
 

     Coulomb Perturbations for ( 4, 4, 4,)  uniform grid of q-points
     (   8q-points):
       N         xq(1)         xq(2)         xq(3) 
       1   0.000000000   0.000000000   0.000000000
       2  -0.250000000   0.250000000  -0.250000000
       3   0.500000000  -0.500000000   0.500000000
       4   0.000000000   0.500000000   0.000000000
       5   0.750000000  -0.250000000   0.750000000
       6   0.500000000   0.000000000   0.500000000
       7   0.000000000  -1.000000000   0.000000000
       8  -0.500000000  -1.000000000   0.000000000
 
     Exchange Grid
     -------------
     E_cutoff(Ry) G_cutoff(crystal) num G vec
        15.00          40.00           64
     nr1t  nr2t  nr3t
          9     9     9
     Global Dimensions   Local  Dimensions   Processor Grid
     .X.   .Y.   .Z.     .X.   .Y.   .Z.     .X.   .Y.   .Z.
       9     9     9       9     9     3       1     1     4
     Array leading dimensions ( nr1x, nr2x, nr3x )   =      9     9     9
     Local number of cell to store the grid ( nrxx ) =        243
     size of the "Z" section of each processor
     nr3p =     3    2    2    2
 
     Correlation Grid
     ----------------
     E_cutoff(Ry) G_cutoff(crystal) num G vec
         6.00          16.00           14
     nr1t  nr2t  nr3t
          6     6     6
     Global Dimensions   Local  Dimensions   Processor Grid
     .X.   .Y.   .Z.     .X.   .Y.   .Z.     .X.   .Y.   .Z.
       5     5     5       5     5     2       1     1     4
     Array leading dimensions ( nr1x, nr2x, nr3x )   =      5     5     5
     Local number of cell to store the grid ( nrxx ) =         50
     size of the "Z" section of each processor
     nr3p =     2    1    1    1
 
     Memory Usage:
 
     G(G, G'; w):            0.0 MB
     G(r, r'; w):            0.4 MB
     W(G, G'; w):            0.0 MB
     W(r, r'):               0.0 MB
     Sigma(G, G'; w):        0.0 MB
     Sigma(r, r'; w):        0.0 MB
     V(G, G'):               0.0 MB
     V(r, r'):               0.1 MB
 

     qpoint does NOT have inversion symmetry

     nsym, nsymq, nrot   24   1  48
 
     Parallelization info
     --------------------
     sticks:   dense  smooth     PW     G-vecs:    dense   smooth      PW
     Min          58      58     20                  569      569     114
     Max          59      59     22                  570      570     115
     Sum         235     235     85                 2277     2277     459
 

     Title: 
     GW band structure along G-X for silicon.                                   

     bravais-lattice index     =            2
     lattice parameter (alat)  =      10.2600  a.u.
     unit-cell volume          =     270.0114 (a.u.)^3
     number of atoms/cell      =            2
     number of atomic types    =            1
     number of electrons       =         8.00
     number of Kohn-Sham states=            4
     kinetic-energy cutoff     =      16.0000  Ry
     charge density cutoff     =      64.0000  Ry
     Exchange-correlation      = PZ ( 1  1  0  0 0 0)

     celldm(1)=  10.260000  celldm(2)=   0.000000  celldm(3)=   0.000000
     celldm(4)=   0.000000  celldm(5)=   0.000000  celldm(6)=   0.000000

     crystal axes: (cart. coord. in units of alat)
               a(1) = (  -0.500000   0.000000   0.500000 )  
               a(2) = (   0.000000   0.500000   0.500000 )  
               a(3) = (  -0.500000   0.500000   0.000000 )  

     reciprocal axes: (cart. coord. in units 2 pi/alat)
               b(1) = ( -1.000000 -1.000000  1.000000 )  
               b(2) = (  1.000000  1.000000  1.000000 )  
               b(3) = ( -1.000000  1.000000 -1.000000 )  

     PseudoPot. # 1 for Si read from file:
     ./Si.pz-vbc.UPF
     MD5 check sum: 6dfa03ddd5817404712e03e4d12deb78
     Pseudo is Norm-conserving, Zval =  4.0
     Generated by new atomic code, or converted to UPF format
     Using radial grid of  431 points,  2 beta functions with: 
                l(1) =   0
                l(2) =   1

     atomic species   valence    mass     pseudopotential
        Si             4.00    28.08600     Si( 1.00)

     24 Sym. Ops. (no inversion) found

   Cartesian axes

     site n.     atom                  positions (alat units)
         1           Si  tau(   1) = (   0.0000000   0.0000000   0.0000000  )
         2           Si  tau(   2) = (   0.2500000   0.2500000   0.2500000  )

     number of k points=   128

     Number of k-points >= 100: set verbosity='high' to print them.

     Dense  grid:     2277 G-vectors     FFT dimensions: (  20,  20,  20)

     Estimated max dynamical RAM per process >       0.36 MB

     Estimated total dynamical RAM >       1.45 MB
Fatal error in PMPI_Alltoall: Invalid communicator, error stack:
PMPI_Alltoall(974): MPI_Alltoall(sbuf=0x33c42c0, scount=295, MPI_DOUBLE_COMPLEX, rbuf=0x33bc580, rcount=295, MPI_DOUBLE_COMPLEX, MPI_COMM_NULL) failed
PMPI_Alltoall(891): Null communicator
Fatal error in PMPI_Alltoall: Invalid communicator, error stack:
PMPI_Alltoall(974): MPI_Alltoall(sbuf=0x36ea4c0, scount=295, MPI_DOUBLE_COMPLEX, rbuf=0x36e27a0, rcount=295, MPI_DOUBLE_COMPLEX, MPI_COMM_NULL) failed
PMPI_Alltoall(891): Null communicator
Fatal error in PMPI_Alltoall: Invalid communicator, error stack:
PMPI_Alltoall(974): MPI_Alltoall(sbuf=0x29c3c00, scount=295, MPI_DOUBLE_COMPLEX, rbuf=0x29bbee0, rcount=295, MPI_DOUBLE_COMPLEX, MPI_COMM_NULL) failed
PMPI_Alltoall(891): Null communicator
Fatal error in PMPI_Alltoall: Invalid communicator, error stack:
PMPI_Alltoall(974): MPI_Alltoall(sbuf=0x32f1540, scount=295, MPI_DOUBLE_COMPLEX, rbuf=0x32e9800, rcount=295, MPI_DOUBLE_COMPLEX, MPI_COMM_NULL) failed
PMPI_Alltoall(891): Null communicator

**Comment by martin-schlipf** [comment]
G vector parallelization is not implemented for SternheimerGW. The only available parallelization levels are pools and images. Run the calculation as
~~~~
mpirun -np 4 gw.x -npool 4 < gw.in > gw.out
~~~~
then it will work.

**Comment by tzyii** [comment]
It works. Thank you very much!
