### ISSUE TITLE
Error in routine diropn (28): error opening xxx.coul1

### ISSUE THREAD

**Issue by tzyii** [QEF/SternheimerGW#2]
When I try to run SternheimerGW, I often get an error like this. And to avoid this error, I need to reduce ecut_exch, ecut_corr or frequency mesh. I suspect the reason is the size of file?  But the free space of the disk is 25T. Here is the ouputs:
      Exchange Grid
     -------------
     E_cutoff(Ry) G_cutoff(crystal) num G vec
        15.00          71.71         6311
     nr1t  nr2t  nr3t
         18    40    20
     Global Dimensions   Local  Dimensions   Processor Grid
     .X.   .Y.   .Z.     .X.   .Y.   .Z.     .X.   .Y.   .Z.
      18    40    20      18    40    20       1     1     1
     Array leading dimensions ( nr1x, nr2x, nr3x )   =     18    40    20
     Local number of cell to store the grid ( nrxx ) =      14400
     size of the "Z" section of each processor
     nr3p =    20
 
     Correlation Grid
     ----------------
     E_cutoff(Ry) G_cutoff(crystal) num G vec
        15.00          71.71         6311
     nr1t  nr2t  nr3t
         18    40    20
     Global Dimensions   Local  Dimensions   Processor Grid
     .X.   .Y.   .Z.     .X.   .Y.   .Z.     .X.   .Y.   .Z.
      18    40    20      18    40    20       1     1     1
     Array leading dimensions ( nr1x, nr2x, nr3x )   =     18    40    20
     Local number of cell to store the grid ( nrxx ) =      14400
     size of the "Z" section of each processor
     nr3p =    20
 
     Memory Usage:
 
     G(G, G'; w):         6372.6 MB
     G(r, r'; w):        33177.6 MB
     W(G, G'; w):          955.9 MB
     W(r, r'):             331.8 MB
     Sigma(G, G'; w):      701.0 MB
     Sigma(r, r'; w):     3649.5 MB
     V(G, G'):              63.7 MB
     V(r, r'):             331.8 MB
 

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine diropn (28):
     error opening ./tmp/_gw0/pyrene-tcnb.coul1
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...

**Comment by martin-schlipf** [comment]
The reason you see this crash is the file I/O. W is written in chunks of num_g_corr^2 * num_freq * 16 (bytes per complex). In your case, num_g_corr is 6311 so that this size exceeds the maximum of an integer (~2e9) for 4-5 frequencies.

I also see that your system has to be very large. The largest system size I tried had a bit less that 1000 G-vectors (for W) and that requires a large number of CPUs (~1000) to run in a reasonable amount of time.

**Comment by tzyii** [comment]
Get it. Thank you.
