### ISSUE TITLE
Does it support the spin-orbit coupling calculation

### ISSUE THREAD

**Issue by yzlan** [QEF/SternheimerGW#4]
Dear all, 
Does the SternheimerGW support  the spin-orbit coupling calculation?
I tried and got an error as follow,
%%%%%%%%%%%%%%%%%%%%%%%%%
     task #         6
     from linear_op.f90 : error #         1
     First dimension of vector psi should be npwx * npol
%%%%%%%%%%%%%%%%%%%%%%%%%

Best regards
Youzhao Lan

**Comment by martin-schlipf** [comment]
No SOC is not supported

**Comment by yzlan** [comment]
Thank you for your reply.
