### ISSUE TITLE
How to obtain the wp for the plasmon-pole (PP) model

### ISSUE THREAD

**Issue by yzlan** [QEF/SternheimerGW#8]
Dear all, 
Could you tell me how to obtain the wp for the plasmon-pole (PP) model?

Best regards.
Youzhao Lan
China

**Comment by Massi9** [comment]
>>Could you tell me how to obtain the wp for the plasmon-pole (PP) model?
you could set it for example to the experimental value of the plasma
frequency of your material or calculate it as wp = sqrt(n*e/m*epsilon_0).

Nourdine

**Comment by yzlan** [comment]
Dear Nourdine,
Thank you
Youzhao Lan
